# Generated by Django 5.0.1 on 2024-02-08 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_rename_bookinstance_bookinstan_delete_mymodelname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstan',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='instance', to='catalog.book'),
        ),
    ]
